#!/usr/bin/env python3
"""
扬说财经 · VIX 恐慌指数预抓取脚本

在 GitHub Actions 部署时运行，从 Yahoo Finance 获取 VIX 指数数据，
生成 data/vix-data.js 供首页静态渲染。

用法：
  python scripts/fetch-vix-data.py          # 抓取并写入 data/vix-data.js
  python scripts/fetch-vix-data.py --print  # 只打印不写入
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TODAY = time.strftime('%Y-%m-%d')

VIX_URL = 'https://query1.finance.yahoo.com/v8/finance/chart/%5EVIX?range=5d&interval=1d'
REQUEST_TIMEOUT = 15

OUTPUT_FILE = os.path.join(ROOT, 'data', 'vix-data.js')


def get_vix_level(vix: float) -> dict:
    """根据 VIX 数值返回恐慌级别和进度条位置（同前端逻辑）"""
    if vix > 30:
        return {'level': '恐慌', 'cls': 'fear', 'pct': min(100, (vix / 50) * 100)}
    if vix > 20:
        return {'level': '中性', 'cls': 'neutral', 'pct': 50 + ((vix - 20) / 10) * 50}
    # 贪婪
    return {'level': '贪婪', 'cls': 'greed', 'pct': max(0, (vix / 20) * 50)}


def fetch_vix() -> dict:
    """从 Yahoo Finance 抓取 VIX 数据，返回结构化的数据字典。失败时返回 None。"""
    req = urllib.request.Request(
        VIX_URL,
        headers={
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': 'application/json',
        }
    )

    try:
        resp = urllib.request.urlopen(req, timeout=REQUEST_TIMEOUT)
        data = json.loads(resp.read().decode('utf-8'))
        result = data['chart']['result'][0]
        quotes = result['indicators']['quote'][0]
        timestamps = result.get('timestamp', [])

        closes = [c for c in quotes.get('close', []) if c is not None]
        if not closes:
            return None

        current_vix = closes[-1]
        prev_vix = closes[-2] if len(closes) >= 2 else current_vix
        change = current_vix - prev_vix
        change_pct = (change / prev_vix * 100) if prev_vix > 0 else 0

        # 取最近一个交易日日期
        last_ts = timestamps[len(closes) - 1] if len(timestamps) > len(closes) - 1 else timestamps[-1] if timestamps else int(time.time())
        last_date = time.strftime('%Y-%m-%d', time.gmtime(last_ts))

        level_info = get_vix_level(current_vix)

        return {
            'current': round(current_vix, 2),
            'prev': round(prev_vix, 2),
            'change': round(change, 2),
            'changePct': round(change_pct, 2),
            'level': level_info['level'],
            'cls': level_info['cls'],
            'pct': round(level_info['pct'], 1),
            'date': last_date,
            'updateTime': time.strftime('%Y-%m-%d %H:%M', time.localtime()),
            'source': 'Yahoo Finance',
        }
    except (urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError,
            KeyError, IndexError, TypeError) as e:
        print(f'  [VIX] 抓取失败: {e}', file=sys.stderr)
        return None


def generate_js(vix_data: dict) -> str:
    """生成 vix-data.js 内容"""
    if vix_data is None:
        return (
            '// VIX 数据暂不可用\n'
            '// Generated by scripts/fetch-vix-data.py\n'
            'window.__VIX_DATA = null;\n'
        )

    return (
        '// VIX 恐慌指数 — 由 scripts/fetch-vix-data.py 自动生成\n'
        f'// 生成时间: {vix_data["updateTime"]} | 数据源: {vix_data["source"]}\n'
        'window.__VIX_DATA = {\n'
        f'  current: {vix_data["current"]},\n'
        f'  prev: {vix_data["prev"]},\n'
        f'  change: {vix_data["change"]},\n'
        f'  changePct: {vix_data["changePct"]},\n'
        f'  level: "{vix_data["level"]}",\n'
        f'  cls: "{vix_data["cls"]}",\n'
        f'  pct: {vix_data["pct"]},\n'
        f'  date: "{vix_data["date"]}",\n'
        f'  updateTime: "{vix_data["updateTime"]}",\n'
        f'  source: "{vix_data["source"]}",\n'
        '};\n'
    )


def main():
    print('[VIX] 正在抓取 VIX 恐慌指数...')
    vix_data = fetch_vix()

    if vix_data:
        arrow = '↑' if vix_data['change'] >= 0 else '↓'
        print(f'  ✅ 当前: {vix_data["current"]}  {vix_data["level"]}')
        print(f'     前一交易日: {vix_data["prev"]}  {arrow} {abs(vix_data["change"])} ({vix_data["changePct"]:+.2f}%)')
        print(f'     日期: {vix_data["date"]}')
    else:
        print('  ⚠️  抓取失败，数据标记为 null')
        print('  首页将显示"暂无数据"')

    js_content = generate_js(vix_data)

    if '--print' in sys.argv:
        print('\n' + js_content)
        return

    # 写入文件
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
    print(f'  📁 写入: data/vix-data.js')


if __name__ == '__main__':
    main()
