#!/usr/bin/env python3
"""
扬说财经 · VIX 恐慌指数预抓取脚本

从 Yahoo Finance 获取 VIX 指数数据，生成 data/vix-data.js 供首页静态渲染。
使用 yfinance 库（自动处理 cookie/crumb 认证）。

用法：
  python scripts/fetch-vix-data.py          # 抓取并写入 data/vix-data.js
  python scripts/fetch-vix-data.py --print  # 只打印不写入
"""

import json
import os
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TODAY = time.strftime('%Y-%m-%d')

OUTPUT_FILE = os.path.join(ROOT, 'data', 'vix-data.js')

# ===== 备用数据：当所有 API 均失败时使用 =====
# 数据来源：WebSearch 交叉验证 (Yahoo Finance / Schwab / TexMetals)
FALLBACK_DATA = {
    'current': 16.76,
    'prev': 17.44,
    'change': -0.68,
    'changePct': -3.90,
    'level': '贪婪',
    'cls': 'greed',
    'pct': 41.9,
    'date': '2026-05-22',
    'updateTime': '2026-05-25 08:00',
    'source': '备用数据 (Yahoo Finance)',
    'note': 'API暂不可用，使用上次有效数据'
}


def get_vix_level(vix: float) -> dict:
    """根据 VIX 数值返回恐慌级别和进度条位置（同前端逻辑）"""
    if vix > 30:
        return {'level': '恐慌', 'cls': 'fear', 'pct': min(100, (vix / 50) * 100)}
    if vix > 20:
        return {'level': '中性', 'cls': 'neutral', 'pct': 50 + ((vix - 20) / 10) * 50}
    return {'level': '贪婪', 'cls': 'greed', 'pct': max(0, (vix / 20) * 50)}


def fetch_via_yfinance() -> dict:
    """使用 yfinance 库获取 VIX 数据"""
    try:
        import yfinance as yf
        vix = yf.Ticker('^VIX')
        hist = vix.history(period='5d')
        if hist.empty:
            return None

        closes = hist['Close'].dropna().values
        if len(closes) == 0:
            return None

        current_vix = float(closes[-1])
        prev_vix = float(closes[-2]) if len(closes) >= 2 else current_vix
        change = current_vix - prev_vix
        change_pct = (change / prev_vix * 100) if prev_vix > 0 else 0

        # 取最近交易日日期
        last_date = hist.index[-1].strftime('%Y-%m-%d')

        level_info = get_vix_level(current_vix)

        return {
            'current': round(current_vix, 2),
            'prev': round(prev_vix, 2),
            'change': round(change, 2),
            'changePct': round(change_pct, 2),
            'level': level_info['level'],
            'cls': level_info['cls'],
            'pct': round(level_info['pct'], 1),
            'date': last_date,
            'updateTime': time.strftime('%Y-%m-%d %H:%M', time.localtime()),
            'source': 'Yahoo Finance (yfinance)',
        }
    except Exception as e:
        print(f'  [VIX] yfinance 抓取失败: {e}', file=sys.stderr)
        return None


def fetch_vix() -> dict:
    """从多个来源依次尝试获取 VIX 数据"""
    # 方案1: yfinance
    data = fetch_via_yfinance()
    if data:
        return data

    # 方案2: 备用数据
    print('  [VIX] 所有 API 失败，使用备用数据', file=sys.stderr)
    fallback = dict(FALLBACK_DATA)
    fallback['updateTime'] = time.strftime('%Y-%m-%d %H:%M', time.localtime())
    return fallback


def generate_js(vix_data: dict) -> str:
    """生成 vix-data.js 内容"""
    if vix_data is None:
        return (
            '// VIX 数据暂不可用\n'
            '// Generated by scripts/fetch-vix-data.py\n'
            'window.__VIX_DATA = null;\n'
        )

    note_line = f'// 备注: {vix_data["note"]}\n' if 'note' in vix_data else ''

    return (
        '// VIX 恐慌指数 — 由 scripts/fetch-vix-data.py 自动生成\n'
        f'// 生成时间: {vix_data["updateTime"]} | 数据源: {vix_data["source"]}\n'
        f'{note_line}'
        'window.__VIX_DATA = {\n'
        f'  current: {vix_data["current"]},\n'
        f'  prev: {vix_data["prev"]},\n'
        f'  change: {vix_data["change"]},\n'
        f'  changePct: {vix_data["changePct"]},\n'
        f'  level: "{vix_data["level"]}",\n'
        f'  cls: "{vix_data["cls"]}",\n'
        f'  pct: {vix_data["pct"]},\n'
        f'  date: "{vix_data["date"]}",\n'
        f'  updateTime: "{vix_data["updateTime"]}",\n'
        f'  source: "{vix_data["source"]}",\n'
        '};\n'
    )


def main():
    print('[VIX] 正在抓取 VIX 恐慌指数...')
    vix_data = fetch_vix()

    if vix_data:
        arrow = '\u2191' if vix_data['change'] >= 0 else '\u2193'
        print(f'  [OK] 当前: {vix_data["current"]}  {vix_data["level"]}')
        print(f'       前一交易日: {vix_data["prev"]}  {arrow} {abs(vix_data["change"])} ({vix_data["changePct"]:+.2f}%)')
        print(f'       日期: {vix_data["date"]}')
        if 'note' in vix_data:
            print(f'       ({vix_data["note"]})')
    else:
        print('  [!!] 抓取失败，数据标记为 null')
        print('       首页将显示"暂无数据"')

    js_content = generate_js(vix_data)

    if '--print' in sys.argv:
        print('\n' + js_content)
        return

    # 写入文件
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
    print(f'  [OK] 写入: data/vix-data.js')


if __name__ == '__main__':
    main()
